name: 'healthcare_clarity'
version: '1.0.0'
config-version: 2

profile: 'healthcare_clarity'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  healthcare_clarity:
    staging:
      +materialized: view
      +schema: jason_chletsos_pennmed_staging
    intermediate:
      +materialized: view
      +schema: jason_chletsos_pennmed_intermediate
    marts:
      +materialized: table
      clinical:
        +schema: jason_chletsos_pennmed_clinical
      financial:
        +schema: jason_chletsos_pennmed_financial

seeds:
  healthcare_clarity:
    +schema: jason_chletsos_pennmed_seeds

data_tests:
  +store_failures: true
  +schema: jason_chletsos_pennmed_test_results
