name: 'healthcare_clarity'
version: '1.0.0'
config-version: 2

profile: 'healthcare_clarity'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  healthcare_clarity:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: table
      clinical:
        +schema: clinical
      financial:
        +schema: financial

seeds:
  healthcare_clarity:
    +schema: seeds

tests:
  +store_failures: true
  +schema: test_results
